-- +migrate Up
CREATE TABLE IF NOT EXISTS books
(
    id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    yop SMALLINT NOT NULL,
    author VARCHAR(255) NOT NULL,
    isbn VARCHAR(13),
    pages INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);

-- +migrate Down
DROP TABLE IF EXISTS books;