// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: books.sql

package reposqlc

import (
	"context"
)

const booksGetAll = `-- name: BooksGetAll :many
SELECT id, title, yop, author, isbn, pages, created_at, updated_at, deleted_at FROM books
`

func (q *Queries) BooksGetAll(ctx context.Context) ([]Book, error) {
	rows, err := q.db.Query(ctx, booksGetAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Yop,
			&i.Author,
			&i.Isbn,
			&i.Pages,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
