// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package reposqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Book struct {
	ID        pgtype.UUID
	Title     string
	Yop       int16
	Author    string
	Isbn      pgtype.Text
	Pages     pgtype.Int4
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}
